# Workflow name
name: Caching using setup-python

# Run this workflow at scheduled times
on: workflow_dispatch

# Create Environment Variables
env:
    author_email_address: ${{ secrets.AUTHOR_EMAIL_ADDRESS }}
    author_name_surname: ${{ secrets.AUTHOR_NAME_SURNAME }}
    recepients_email: ${{ secrets.RECEPIENTS_EMAIL }}
    search_cities_list: ${{ secrets.SEARCH_CITIES_LIST }}
    zone_info: ${{ secrets.ZONE_INFO }}
    smtp_server: ${{ secrets.SMTP_SERVER }}
    smtp_port: ${{ secrets.SMTP_PORT }}
    smtp_username: ${{ secrets.SMTP_USERNAME }}
    mail_app_password: ${{ secrets.MAIL_APP_PASSWORD }}
    website_url_root: ${{ secrets.WEBSITE_URL_ROOT }}
    search_requirements: ${{ secrets.SEARCH_REQUIREMENTS }}
    mask: ${{ secrets.MASK }}    

# Allow write permissions to the remote repo
permissions:
  contents: write

# Create Jobs
jobs:
    run_python_via_powershell:
        runs-on: ${{ matrix.os }}
        strategy:
            max-parallel: 1
            matrix:
                os: [windows-latest]
                python-version: ['3.11']
            fail-fast: false

        # Define Job Steps
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4

            # Caching using setup-python
            - name: Setup Python Version ${{ matrix.python-version }}
              uses: actions/setup-python@v5
              with:
                python-version: ${{ matrix.python-version }}
                cache: 'pip'

            - name: Install Packages
              # run: pip install -r requirements.txt
              run: |
                pip install --force-reinstall -r requirements.txt --only-binary :all:

            - name: List All Installed Packages
              run: pip list packages

            - name: Run Python Script via Powershell
              shell: pwsh
              run: python watchdog.py

            # - name: Push New Changes to Remote
            #   run: |
            #     git config --global user.name ${{ secrets.AUTHOR_NAME_SURNAME }}
            #     git config --global user.email ${{ secrets.AUTHOR_EMAIL_ADDRESS }}
            #     git add database
            #     git commit -m "[refactor]: Update database via automated action"
            #     git push origin main