# Workflow name
name: Caching using pythonlocation

# Run this workflow at scheduled times
on: push

# Create Environment Variables
env:
    author_email_address: ${{ secrets.AUTHOR_EMAIL_ADDRESS }}
    author_name_surname: ${{ secrets.AUTHOR_NAME_SURNAME }}
    recepients_email: ${{ secrets.RECEPIENTS_EMAIL }}
    search_cities_list: ${{ secrets.SEARCH_CITIES_LIST }}
    zone_info: ${{ secrets.ZONE_INFO }}
    smtp_server: ${{ secrets.SMTP_SERVER }}
    smtp_port: ${{ secrets.SMTP_PORT }}
    smtp_username: ${{ secrets.SMTP_USERNAME }}
    mail_app_password: ${{ secrets.MAIL_APP_PASSWORD }}
    website_url_root: ${{ secrets.WEBSITE_URL_ROOT }}
    search_requirements: ${{ secrets.SEARCH_REQUIREMENTS }}
    mask: ${{ secrets.MASK }}

# Allow write permissions to the remote repo
permissions:
  contents: write

# Create Jobs
jobs:
    run_python_via_powershell:
        runs-on: ${{ matrix.os }}
        strategy:
            # max-parallel: 1
            matrix:
                os: [windows-latest]
                python-version: ['3.11']
            fail-fast: false

        steps:
            - name: Checkout Code
              uses: actions/checkout@v2

            - name: Setup Python Version ${{ matrix.python-version }}
              uses: actions/setup-python@v1
              with:
                python-version: ${{ matrix.python-version }}

            # Caching using pythonlocation
            - name: Cache Python Packages
              uses: actions/cache@v2
              id: cache-packages
              with:
                path: ${{ env.pythonLocation }}
                key: ${{ runner.os }}-pip-${{ env.pythonLocation }}-${{ hashFiles('**/requirements.txt') }}
                restore-keys: |
                  ${{ runner.os }}-pip-${{ env.pythonLocation }}-

            - name: Install Packages
              if: steps.cache-env.outputs.cache-hit != 'true'
              run: pip install -r requirements.txt
            
            - name: Check Installed Packages
              run: echo "Cache Hit - ${{ steps.cache-packages.outputs.cache-hit }}"; pip list packages

            - name: Run Python Script via Powershell
              shell: pwsh
              run: python watchdog.py

            - name: Push new changes to remote
              run: |
                git config --global user.name ${{ secrets.AUTHOR_NAME_SURNAME }}
                git config --global user.email ${{ secrets.AUTHOR_EMAIL_ADDRESS }}
                git add database
                git commit -m "[refactor]: Update database via automated action"
                git push origin main